services:
  jira:
    image: ghcr.io/arvingrep/atlassian-jira:${JIRA_VERSION:-9.6.0}-example-agent

  confluence:
    image: ghcr.io/arvingrep/atlassian-confluence:${CONFLUENCE_VERSION:-7.19.7}-example-agent
