services:
  jira:
    image: ${JIRA_LOCAL_IMAGE}
    build:
      context: .
      dockerfile: jira/Dockerfile
      args:
        BASE_IMAGE: ${JIRA_BASE_IMAGE}

  confluence:
    image: ${CONFLUENCE_LOCAL_IMAGE}
    build:
      context: .
      dockerfile: confluence/Dockerfile
      args:
        BASE_IMAGE: ${CONFLUENCE_BASE_IMAGE}
